name: Publish NuGet Package

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Validate Tag
        run: |
          if [[ ! ${{ github.ref }} =~ ^refs/tags/v([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
            echo "Invalid Tag & Version"
            exit 1
          fi

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore Dependencies
        run: dotnet restore

      - name: Run Tests
        run: dotnet test --configuration Release --no-restore

      - name: Build Project
        run: dotnet build --configuration Release --no-restore

      - name: Create NuGet Package
        run: dotnet pack --configuration Release

      - name: Set Version and Package Path
        id: vars
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
          PACKAGE_PATH=$(find bin/Release -name "*.nupkg" | head -n 1)
          echo "PACKAGE_PATH=$PACKAGE_PATH" >> $GITHUB_ENV
          echo "PACKAGE_NAME=$(basename "$PACKAGE_PATH")" >> $GITHUB_ENV
        shell: bash

      - name: Push To NuGet Gallery
        run: |
          dotnet nuget push "$PACKAGE_PATH" \
            --source https://api.nuget.org/v3/index.json \
            --api-key ${{ secrets.NUGET_API_KEY }} \
            --skip-duplicate

      - name: Push To GitHub Packages
        run: |
          dotnet nuget push "$PACKAGE_PATH" \
            --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
            --api-key ${{ secrets.GH_API_SECRET }} \
            --skip-duplicate

      - name: Create GitHub Release and Upload Asset
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
          files: ${{ env.PACKAGE_PATH }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_API_SECRET }}